./extract_mhwg_monster.pl \
mhwg_extracts/monsters/3200.html \
mhwg_extracts/monsters/4320.html \
mhwg_extracts/monsters/3801.html \
mhwg_extracts/monsters/4325.html \
mhwg_extracts/monsters/4318.html \
mhwg_extracts/monsters/3800.html \
mhwg_extracts/monsters/4255.html \
mhwg_extracts/monsters/4215.html \
mhwg_extracts/monsters/3203.html \
mhwg_extracts/monsters/3803.html \
mhwg_extracts/monsters/4257.html \
mhwg_extracts/monsters/3805.html \
mhwg_extracts/monsters/4253.html \
mhwg_extracts/monsters/4245.html \
mhwg_extracts/monsters/4204.html \
mhwg_extracts/monsters/4200.html \
mhwg_extracts/monsters/4217.html \
mhwg_extracts/monsters/4202.html \
mhwg_extracts/monsters/4319.html \
mhwg_extracts/monsters/3804.html \
mhwg_extracts/monsters/4216.html \
mhwg_extracts/monsters/3204.html \
mhwg_extracts/monsters/4205.html \
mhwg_extracts/monsters/4252.html \
mhwg_extracts/monsters/4201.html \
mhwg_extracts/monsters/4203.html \
mhwg_extracts/monsters/4244.html \
mhwg_extracts/monsters/4256.html \
mhwg_extracts/monsters/4324.html \
mhwg_extracts/monsters/3806.html > /tmp/mhwg_mons.xml

./extract_kira_monster.pl \
kiranico_extracts/monsters/anjanath \
kiranico_extracts/monsters/azure-rathalos \
kiranico_extracts/monsters/barroth \
kiranico_extracts/monsters/bazelgeuse \
kiranico_extracts/monsters/black-diablos \
kiranico_extracts/monsters/diablos \
kiranico_extracts/monsters/dodogama \
kiranico_extracts/monsters/great-girros \
kiranico_extracts/monsters/great-jagras \
kiranico_extracts/monsters/jyuratodus \
kiranico_extracts/monsters/kirin \
kiranico_extracts/monsters/kulu-ya-ku \
kiranico_extracts/monsters/kushala-daora \
kiranico_extracts/monsters/lavasioth \
kiranico_extracts/monsters/legiana \
kiranico_extracts/monsters/nergigante \
kiranico_extracts/monsters/odogaron \
kiranico_extracts/monsters/paolumu \
kiranico_extracts/monsters/pink-rathian \
kiranico_extracts/monsters/pukei-pukei \
kiranico_extracts/monsters/radobaan \
kiranico_extracts/monsters/rathalos \
kiranico_extracts/monsters/rathian \
kiranico_extracts/monsters/teostra \
kiranico_extracts/monsters/tobi-kadachi \
kiranico_extracts/monsters/tzitzi-ya-ku \
kiranico_extracts/monsters/uragaan \
kiranico_extracts/monsters/vaal-hazak \
kiranico_extracts/monsters/xenojiiva \
kiranico_extracts/monsters/zorah-magdaros > /tmp/kira_mons.xml
