./extract_mhwg_monster.pl \
mhwg_extracts/monsters/3200.html \
mhwg_extracts/monsters/4320.html \
mhwg_extracts/monsters/3801.html \
mhwg_extracts/monsters/4325.html \
mhwg_extracts/monsters/4318.html \
mhwg_extracts/monsters/3800.html \
mhwg_extracts/monsters/4255.html \
mhwg_extracts/monsters/4215.html \
mhwg_extracts/monsters/3203.html \
mhwg_extracts/monsters/3803.html \
mhwg_extracts/monsters/4257.html \
mhwg_extracts/monsters/3805.html \
mhwg_extracts/monsters/4253.html \
mhwg_extracts/monsters/4245.html \
mhwg_extracts/monsters/4204.html \
mhwg_extracts/monsters/4200.html \
mhwg_extracts/monsters/4217.html \
mhwg_extracts/monsters/4202.html \
mhwg_extracts/monsters/4319.html \
mhwg_extracts/monsters/3804.html \
mhwg_extracts/monsters/4216.html \
mhwg_extracts/monsters/3204.html \
mhwg_extracts/monsters/4205.html \
mhwg_extracts/monsters/4252.html \
mhwg_extracts/monsters/4201.html \
mhwg_extracts/monsters/4203.html \
mhwg_extracts/monsters/4244.html \
mhwg_extracts/monsters/4256.html \
mhwg_extracts/monsters/4324.html \
mhwg_extracts/monsters/3806.html \
mhwg_extracts/monsters/4254.html \
mhwg_extracts/monsters/4358.html \
mhwg_extracts/monsters/4321.html \
mhwg_extracts/monsters/4361.html \
mhwg_extracts/monsters/4363.html \
mhwg_extracts/monsters/4364.html \
mhwg_extracts/monsters/4365.html \
mhwg_extracts/monsters/4369.html \
mhwg_extracts/monsters/4372.html \
mhwg_extracts/monsters/4368.html \
mhwg_extracts/monsters/4366.html \
mhwg_extracts/monsters/4367.html \
mhwg_extracts/monsters/4373.html \
mhwg_extracts/monsters/4379.html \
mhwg_extracts/monsters/4380.html \
mhwg_extracts/monsters/4381.html \
mhwg_extracts/monsters/4382.html \
mhwg_extracts/monsters/4385.html \
mhwg_extracts/monsters/4387.html \
mhwg_extracts/monsters/4388.html \
mhwg_extracts/monsters/4389.html \
mhwg_extracts/monsters/4391.html \
mhwg_extracts/monsters/4393.html \
mhwg_extracts/monsters/4401.html \
mhwg_extracts/monsters/4402.html \
mhwg_extracts/monsters/4403.html \
mhwg_extracts/monsters/4404.html \
mhwg_extracts/monsters/4405.html \
mhwg_extracts/monsters/4406.html \
mhwg_extracts/monsters/4407.html \
mhwg_extracts/monsters/4408.html \
mhwg_extracts/monsters/4409.html \
mhwg_extracts/monsters/4413.html \
mhwg_extracts/monsters/4414.html > /tmp/mhwg_mons.xml

./extract_kira_monster.pl \
kiranico_extracts/monsters/anjanath \
kiranico_extracts/monsters/azure-rathalos \
kiranico_extracts/monsters/barroth \
kiranico_extracts/monsters/bazelgeuse \
kiranico_extracts/monsters/black-diablos \
kiranico_extracts/monsters/diablos \
kiranico_extracts/monsters/dodogama \
kiranico_extracts/monsters/great-girros \
kiranico_extracts/monsters/great-jagras \
kiranico_extracts/monsters/jyuratodus \
kiranico_extracts/monsters/kirin \
kiranico_extracts/monsters/kulu-ya-ku \
kiranico_extracts/monsters/kushala-daora \
kiranico_extracts/monsters/lavasioth \
kiranico_extracts/monsters/legiana \
kiranico_extracts/monsters/nergigante \
kiranico_extracts/monsters/odogaron \
kiranico_extracts/monsters/paolumu \
kiranico_extracts/monsters/pink-rathian \
kiranico_extracts/monsters/pukei-pukei \
kiranico_extracts/monsters/radobaan \
kiranico_extracts/monsters/rathalos \
kiranico_extracts/monsters/rathian \
kiranico_extracts/monsters/teostra \
kiranico_extracts/monsters/tobi-kadachi \
kiranico_extracts/monsters/tzitzi-ya-ku \
kiranico_extracts/monsters/uragaan \
kiranico_extracts/monsters/vaal-hazak \
kiranico_extracts/monsters/xenojiiva \
kiranico_extracts/monsters/zorah-magdaros \
kiranico_extracts/monsters/deviljho > /tmp/kira_mons.xml
#kiranico_extracts/monsters/kulve-taroth

./merge_monsters.pl translations.xml /tmp/kira_mons.xml /tmp/mhwg_mons.xml
